//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FotbollsVMKlocka.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string Hostname {
            get {
                return ((string)(this["Hostname"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/clock")]
        public string TemplateNameClock {
            get {
                return ((string)(this["TemplateNameClock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Overtime")]
        public string BottomFlarp {
            get {
                return ((string)(this["BottomFlarp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ALG#Algeriet</string>
  <string>ARG#Argentina</string>
  <string>AUS#Australien</string>
  <string>BRA#Brasilien</string>
  <string>CHI#Chile</string>
  <string>DEN#Danmark</string>
  <string>CIV#Elfenbenskusten</string>
  <string>ENG#England</string>
  <string>FRA#Frankrike</string>
  <string>GHA#Ghana</string>
  <string>GRE#Grekland</string>
  <string>NED#Holland</string>
  <string>HON#Honduras</string>
  <string>ITA#Italien</string>
  <string>JPN#Japan</string>
  <string>CMR#Kamerun</string>
  <string>MEX#Mexiko</string>
  <string>NGA#Nigeria</string>
  <string>PRK#Nordkorea</string>
  <string>NZL#Nya Zeeland</string>
  <string>PAR#Paraguay</string>
  <string>POR#Portugal</string>
  <string>SUI#Schweiz</string>
  <string>SRB#Serbien</string>
  <string>SVK#Slovakien</string>
  <string>SVN#Slovenien</string>
  <string>ESP#Spanien</string>
  <string>RSA#Sydafrika</string>
  <string>KOR#Sydkorea</string>
  <string>GER#Tyskland</string>
  <string>URU#Uruguay</string>
  <string>USA#USA</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Teams {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Teams"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/telegram")]
        public string TemplateNameTickerUp {
            get {
                return ((string)(this["TemplateNameTickerUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/telegram")]
        public string TemplateNameTickerNere {
            get {
                return ((string)(this["TemplateNameTickerNere"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GraphicsLayerClock {
            get {
                return ((int)(this["GraphicsLayerClock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GraphicsLayerExternalTicker {
            get {
                return ((int)(this["GraphicsLayerExternalTicker"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crawlTextUp")]
        public string FieldNameTickerUp {
            get {
                return ((string)(this["FieldNameTickerUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crawlTextDown")]
        public string FieldNameTickerDown {
            get {
                return ((string)(this["FieldNameTickerDown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/4021")]
        public string Name1RowDown {
            get {
                return ((string)(this["Name1RowDown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/4024")]
        public string Name1RowUp {
            get {
                return ((string)(this["Name1RowUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>---</string>
  <string>SVT1</string>
  <string>SVT2</string>
  <string>SVT24</string>
  <string>SVTB</string>
  <string>SVTHD</string>
  <string>SVTPLAY</string>
  <string>TV4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Logos {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Logos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/countdown")]
        public string TemplateNameCountDown {
            get {
                return ((string)(this["TemplateNameCountDown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/facebook_helsida")]
        public string TemplateNameFacebookFull {
            get {
                return ((string)(this["TemplateNameFacebookFull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FotbollsVM2010/facebookSimpel")]
        public string TemplateNameFacebookBottom {
            get {
                return ((string)(this["TemplateNameFacebookBottom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("facebook.txt")]
        public string FileNameFacebookComments {
            get {
                return ((string)(this["FileNameFacebookComments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CasparChannel {
            get {
                return ((int)(this["CasparChannel"]));
            }
        }
    }
}
